ibm-portworx: v0.2.0
- Applies fixes from testing to allow the portworx instance to be created correctly
- Adds helm post-delete hook and argocd postsync hook to clean up lingering Portworx resources in kube-system namespace

closes #336

Signed-off-by: Sean Sundberg <seansund@us.ibm.com>

diff --git a/stable/ibm-portworx/templates/configmap.yaml b/stable/ibm-portworx/templates/configmap.yaml
--- a/stable/ibm-portworx/templates/configmap.yaml
+++ b/stable/ibm-portworx/templates/configmap.yaml
@@ -4,17 +4,89 @@ metadata:
   name: {{ include "ibm-portworx.fullname" . }}
   annotations:
     argocd.argoproj.io/sync-wave: "-5"
+    helm.sh/hook-weight: "-5"
   labels:
     {{- include "ibm-portworx.labels" . | nindent 4 }}
 data:
+  support-functions.sh: |
+    #!/usr/bin/env bash
+
+    API_VERSION="2021-04-06"
+
+    get_token() {
+      local API_KEY="$1"
+
+      TOKEN=$(curl -s -X POST "https://iam.cloud.ibm.com/identity/token" \
+        -H "Content-Type: application/x-www-form-urlencoded" \
+        -d "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=${API_KEY}" | jq -r '.access_token')
+
+      if [[ -z "${TOKEN}" ]]; then
+        echo "Error retrieving auth token" >&2
+        exit 1
+      fi
+    }
+
+    get_volume_id() {
+      local REGION="$1"
+      local NAME="$2"
+
+      VOLUME_ID=$(curl -s -X GET "https://${REGION}.iaas.cloud.ibm.com/v1/volumes?version=${API_VERSION}&generation=2&name=${NAME}" \
+        -H "Authorization: Bearer ${TOKEN}" | \
+        jq -r --arg NAME "${NAME}" '.volumes[] | select(.name == $NAME) | .id // empty')
+    }
+
+    create_volume() {
+      local REGION="$1"
+      local NAME="$2"
+      local DATA="$3"
+
+      curl -s -X POST "https://${REGION}.iaas.cloud.ibm.com/v1/volumes?version=${API_VERSION}&generation=2" \
+        -H "Authorization: Bearer $TOKEN" \
+        -d "${DATA}"
+
+      get_volume_id "${REGION}" "${NAME}"
+    }
+
+    wait_for_volume() {
+      local REGION="$1"
+      local VOLUME_ID="$2"
+
+      echo "Waiting for volume to be ready: ${VOLUME_ID}"
+
+      count=0
+      STATUS="pending"
+      while [[ "${STATUS}" == "pending" ]] || [[ $count -gt 20 ]]; do
+        local VOLUME=$(curl -s -X GET "https://${REGION}.iaas.cloud.ibm.com/v1/volumes/${VOLUME_ID}?version=${API_VERSION}&generation=2" \
+          -H "Authorization: Bearer ${TOKEN}" | jq -c '.')
+
+        STATUS=$(echo "${VOLUME}" | jq -r '.status')
+
+        if [[ "${STATUS}" == "pending" ]]; then
+          echo "Volume is still pending. Sleeping for 30 seconds..."
+          count=$((count + 1))
+          sleep 30
+        fi
+      done
+
+      if [[ $count -gt 20 ]]; then
+        echo "Timed out waiting for volume: ${VOLUME_ID}" >&2
+        exit 1
+      fi
+
+      echo "Volume is available: ${VOLUME_ID}"
+    }
   volume-attach.sh: |+
     #!/usr/bin/env bash
 
-    NODE_NAME="$1"
-    RESOURCE_GROUP_ID="$2"
+    SCRIPT_DIR=$(cd $(dirname "$0"); pwd -P)
 
-    if [[ -z "${NODE_NAME}" ]] || [[ -z "${RESOURCE_GROUP_ID}" ]]; then
-      echo "usage: attach-volume.sh NODE_NAME RESOURCE_GROUP_ID" >&2
+    RESOURCE_GROUP_ID="$1"
+    REGION="$2"
+    WORKER_ID="$3"
+    CLUSTER_ID="$4"
+
+    if [[ -z "${RESOURCE_GROUP_ID}" ]] || [[ -z "${REGION}" ]] ||  [[ -z "${WORKER_ID}" ]] || [[ -z "${CLUSTER_ID}" ]]; then
+      echo "usage: volume-attach.sh RESOURCE_GROUP_ID REGION WORKER_ID CLUSTER_ID" >&2
       exit 1
     fi
 
@@ -38,22 +110,13 @@ data:
       exit 1
     fi
 
-    REGION=$(kubectl get node "${NODE_NAME}" -o json | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/region"]')
-    WORKER_ID=$(kubectl get node "${NODE_NAME}" -o json | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/worker-id"]')
-    PROVIDER_ID=$(kubectl get node "${NODE_NAME}" -o json | jq -r '.spec.providerID')
-    CLUSTER_ID=$(echo "${PROVIDER_ID}" | sed -E 's~ibm://.*/([^/]+)/.+~\1~g')
+    source "${SCRIPT_DIR}/support-functions.sh"
 
     NAME="pwx-${WORKER_ID}"
 
-    export TOKEN=$(curl -s -X POST "https://iam.cloud.ibm.com/identity/token" \
-      -H "Content-Type: application/x-www-form-urlencoded" \
-      -d "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=${IBMCLOUD_API_KEY}" | jq -r '.access_token')
+    get_token "${IBMCLOUD_API_KEY}"
 
-    API_VERSION="2021-04-06"
-
-    VOLUME_ID=$(curl -X GET "https://${REGION}.iaas.cloud.ibm.com/v1/volumes?version=${API_VERSION}&generation=2" \
-      -H "Authorization: ${TOKEN}" | \
-      jq -r --arg NAME "${NAME}" '.volumes[] | select(.name == $NAME) | .id // empty')
+    get_volume_id "${REGION}" "${NAME}"
 
     # Before creating, check to see if attachment for volume is already present
     if ! RESPONSE=$(curl -s -X GET \
@@ -98,11 +161,15 @@ data:
   volume-attachment-destroy.sh: |
     #!/bin/bash
 
-    NODE_NAME="$1"
-    RESOURCE_GROUP_ID="$2"
+    SCRIPT_DIR=$(cd $(dirname "$0"); pwd -P)
 
-    if [[ -z "${NODE_NAME}" ]] || [[ -z "${RESOURCE_GROUP_ID}" ]]; then
-      echo "usage: attach-volume.sh NODE_NAME RESOURCE_GROUP_ID" >&2
+    RESOURCE_GROUP_ID="$1"
+    REGION="$2"
+    WORKER_ID="$3"
+    CLUSTER_ID="$4"
+
+    if [[ -z "${RESOURCE_GROUP_ID}" ]] || [[ -z "${REGION}" ]] ||  [[ -z "${WORKER_ID}" ]] || [[ -z "${CLUSTER_ID}" ]]; then
+      echo "usage: volume-attachment-destroy.sh RESOURCE_GROUP_ID REGION WORKER_ID CLUSTER_ID" >&2
       exit 1
     fi
 
@@ -126,22 +193,13 @@ data:
       exit 1
     fi
 
-    REGION=$(kubectl get node "${NODE_NAME}" -o json | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/region"]')
-    WORKER_ID=$(kubectl get node "${NODE_NAME}" -o json | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/worker-id"]')
-    PROVIDER_ID=$(kubectl get node "${NODE_NAME}" -o json | jq -r '.spec.providerID')
-    CLUSTER_ID=$(echo "${PROVIDER_ID}" | sed -E 's~ibm://.*/([^/]+)/.+~\1~g')
+    source "${SCRIPT_DIR}/support-functions.sh"
 
     NAME="pwx-${WORKER_ID}"
 
-    export TOKEN=$(curl -s -X POST "https://iam.cloud.ibm.com/identity/token" \
-      -H "Content-Type: application/x-www-form-urlencoded" \
-      -d "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=${IBMCLOUD_API_KEY}" | jq -r '.access_token')
+    get_token "${IBMCLOUD_API_KEY}"
 
-    API_VERSION="2021-04-06"
-
-    VOLUME_ID=$(curl -X GET "https://${REGION}.iaas.cloud.ibm.com/v1/volumes?version=${API_VERSION}&generation=2" \
-      -H "Authorization: ${TOKEN}" | \
-      jq -r --arg NAME "${NAME}" '.volumes[] | select(.name == $NAME) | .id // empty')
+    get_volume_id "${REGION}" "${NAME}"
 
     echo "Detaching volume $VOLUME_ID from worker $WORKER_ID"
 
@@ -173,6 +231,8 @@ data:
   volume-create.sh: |
     #!/usr/bin/env bash
 
+    SCRIPT_DIR=$(cd $(dirname "$0"); pwd -P)
+
     NODE_NAME="$1"
     RESOURCE_GROUP_ID="$2"
 
@@ -187,24 +247,30 @@ data:
     fi
 
     if ! command -v curl 1> /dev/null 2> /dev/null; then
-      echo "curl command not found" > &2
+      echo "curl command not found" >&2
       exit 1
     fi
 
     if ! command -v jq 1> /dev/null 2> /dev/null; then
-      echo "jq command not found" > &2
+      echo "jq command not found" >&2
       exit 1
     fi
 
     if ! command -v kubectl 1> /dev/null 2> /dev/null; then
-      echo "kubectl command not found" > &2
+      echo "kubectl command not found" >&2
       exit 1
     fi
 
+    source "${SCRIPT_DIR}/support-functions.sh"
+
     ## Lookup zone and resource group from the cluster
-    REGION=$(kubectl get node "${NODE_NAME}" -o json | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/region"]')
-    ZONE=$(kubectl get node "${NODE_NAME}" -o json | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/zone"]')
-    WORKER_ID=$(kubectl get node "${NODE_NAME}" -o json | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/worker-id"]')
+    NODE_JSON=$(kubectl get node "${NODE_NAME}" -o json)
+
+    REGION=$(echo "${NODE_JSON}" | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/region"]')
+    ZONE=$(echo "${NODE_JSON}" | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/zone"]')
+    WORKER_ID=$(echo "${NODE_JSON}" | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/worker-id"]')
+
+    echo "Node values: region=${REGION}, zone=${ZONE}, workerId=${WORKER_ID}"
 
     NAME="pwx-${WORKER_ID}"
 
@@ -228,8 +294,8 @@ data:
       --arg NAME "${NAME}" \
       --arg ZONE "${ZONE}" \
       --arg RESOURCE_GROUP_ID "${RESOURCE_GROUP_ID}" \
-      --arg IOPS "${IOPS}" \
-      --arg CAPACITY "${CAPACITY}" \
+      --argjson IOPS "${IOPS}" \
+      --argjson CAPACITY "${CAPACITY}" \
       --arg PROFILE "${PROFILE}" \
       '{"name": $NAME, "iops": $IOPS, "capacity": $CAPACITY, "zone": {"name": $ZONE}, "profile": {"name": $PROFILE}, "resource_group": {"id": $RESOURCE_GROUP_ID}}' > /tmp/volume-request.json
 
@@ -240,47 +306,60 @@ data:
         rm /tmp/volume-request.json.bak
     fi
 
-    VPC_API_ENDPOINT="https://${REGION}.iaas.cloud.ibm.com"
-    API_VERSION="2021-04-06"
+    echo "Getting auth token"
 
-    export TOKEN=$(curl -s -X POST "https://iam.cloud.ibm.com/identity/token" \
-      -H "Content-Type: application/x-www-form-urlencoded" \
-      -d "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=${IBMCLOUD_API_KEY}" | jq -r '.access_token')
+    get_token "${IBMCLOUD_API_KEY}" || exit 1
 
+    echo "Looking up exiting volume: ${NAME}"
 
     ## Check if volume already exists
-    VOLUME_ID=$(curl -X GET "${VPC_API_ENDPOINT}/v1/volumes?version=${API_VERSION}&generation=2" \
-      -H "Authorization: $TOKEN" | \
-      jq -r --arg NAME "${NAME}" '.volumes[] | select(.name == $NAME) | .id // empty')
+    get_volume_id "${REGION}" "${NAME}"
 
-    if [[ -n "${VOLUME_ID}" ]]; then
-      echo "Volume already exists: ${NAME}"
-      exit 0
+    if [[ -z "${VOLUME_ID}" ]]; then
+      echo "Volume not found: ${NAME}"
+
+      echo "Creating volume: "
+      jq '.' /tmp/volume-request.json
+
+      create_volume "${REGION}" $(jq -c '.' /tmp/volume-request.json)
+    else
+      echo "Existing volume found: ${NAME}"
     fi
 
-    curl -X POST "${VPC_API_ENDPOINT}/v1/volumes?version=${API_VERSION}&generation=2" \
-      -H "Authorization: $TOKEN" \
-      -d @/tmp/volume-request.json
+    echo "Waiting for volume"
+
+    wait_for_volume "${REGION}" "${VOLUME_ID}"
   volume-manage.sh: |
     #!/usr/bin/env bash
 
     SCRIPT_DIR=$(cd $(dirname "$0"); pwd -P)
 
-    export NODE_NAME="$1"
-    export RESOURCE_GROUP_ID="$2"
+    if [[ -z "${NODE_NAME}" ]] || [[ -z "${RESOURCE_GROUP_ID}" ]]; then
+      echo "NODE_NAME and RESOURCE_GROUP_ID should be provided as environment variables" >&2
+      exit 1
+    fi
+
+    NODE_JSON=$(kubectl get node "${NODE_NAME}" -o json)
+
+    REGION=$(echo "${NODE_JSON}" | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/region"]')
+    WORKER_ID=$(echo "${NODE_JSON}" | jq -r '.metadata.labels["ibm-cloud.kubernetes.io/worker-id"]')
+    PROVIDER_ID=$(echo "${NODE_JSON}" | jq -r '.spec.providerID')
+    CLUSTER_ID=$(echo "${PROVIDER_ID}" | sed -E 's~ibm://.*/([^/]+)/.+~\1~g')
+
+    echo "Node values: region=${REGION}, workerId=${WORKER_ID}, clusterId=${CLUSTER_ID}"
 
     exit_script() {
         echo "SIGTERM received!"
         echo "Cleaning up volume attachment"
-        "${SCRIPT_DIR}/volume-attachment-destroy.sh" "${NODE_NAME}" "${RESOURCE_GROUP_ID}"
+        "${SCRIPT_DIR}/volume-attachment-destroy.sh" "${RESOURCE_GROUP_ID}" "${REGION}" "${WORKER_ID}" "${CLUSTER_ID}"
+        EXIT="true"
     }
 
-    trap exit_script SIGTERM
+    trap exit_script SIGINT SIGTERM
 
-    "${SCRIPT_DIR}/volume-attach.sh" "${NODE_NAME}" "${RESOURCE_GROUP_ID}"
+    "${SCRIPT_DIR}/volume-attach.sh" "${RESOURCE_GROUP_ID}" "${REGION}" "${WORKER_ID}" "${CLUSTER_ID}"
 
-    while true; do sleep 300; done
-  wipe_portworx.sh: "#!/bin/bash\n\n\n# Docs for cleaning up Portworx installation at: https://cloud.ibm.com/docs/containers?topic=containers-portworx#portworx_cleanup\n# Additional utilities for cleaning up Portworx installation available at https://github.com/IBM/ibmcloud-storage-utilities/blob/master/px-utils/px_cleanup/px-wipe.sh\n\necho \"Wiping Portworx from cluster: $CLUSTER\"\n\nPATH=$BIN_DIR:$PATH\n\ncurl  -fSsL https://raw.githubusercontent.com/IBM/ibmcloud-storage-utilities/master/px-utils/px_cleanup/px-wipe.sh | bash -s -- --talismanimage icr.io/ext/portworx/talisman --talismantag 1.1.0 --wiperimage icr.io/ext/portworx/px-node-wiper --wipertag 2.5.0 --force\n\necho \"removing the portworx helm from the cluster\"\n_rc=0\nhelm_release=$(helm ls -a --output json | jq -r '.[]|select(.name==\"portworx\") | .name')\nif [ -z \"$helm_release\" ];\nthen\n  echo \"Unable to find helm release for portworx.  Ensure your helm client is at version 3 and has access to the cluster.\";\nelse\n  helm uninstall portworx || _rc=$?\n  if [ $_rc -ne 0 ]; then\n    echo \"error removing the helm release\"\n    #exit 1;\n  fi\nfi\n\necho \"removing all portworx storage classes\"\nkubectl get sc -A | grep portworx | awk '{ print $1 }' > sc.tmp\nwhile read in; do\n  kubectl delete sc \"$in\"\ndone < sc.tmp\nrm -rf sc.tmp\n\necho \"removing portworx artifacts\"\nkubectl delete serviceaccount -n kube-system portworx-hook --ignore-not-found=true\nkubectl delete clusterrole -n kube-system portworx-hook --ignore-not-found=true\nkubectl delete clusterrolebinding -n kube-system portworx-hook --ignore-not-found=true\n\nkubectl delete Service portworx-service -n kube-system --ignore-not-found=true\nkubectl delete Service portworx-api -n kube-system --ignore-not-found=true\n\nkubectl delete serviceaccount -n kube-system portworx-hook --ignore-not-found=true \nkubectl delete clusterrole portworx-hook -n kube-system --ignore-not-found=true\nkubectl delete clusterrolebinding portworx-hook -n kube-system --ignore-not-found=true\n\nkubectl delete job -n kube-system talisman --ignore-not-found=true\nkubectl delete serviceaccount -n kube-system talisman-account --ignore-not-found=true \nkubectl delete clusterrolebinding talisman-role-binding --ignore-not-found=true \nkubectl delete crd volumeplacementstrategies.portworx.io --ignore-not-found=true\nkubectl delete configmap -n kube-system portworx-pvc-controller --ignore-not-found=true\n\nkubectl delete secret -n default sh.helm.release.v1.portworx.v1 --ignore-not-found=true\n\n# use the following command to verify all portworks resources are gone.  If you see a result here, it didn't work\n# kubectl get all -A | grep portworx"
+    while [[ "${EXIT}" != "true" ]]; do sleep 10; done
   write-config-secret.sh: |
     #!/usr/bin/env bash
 
@@ -288,11 +367,24 @@ data:
     NAMESPACE="$2"
     SECRET_NAME="$3"
 
+    if [[ -z "${NODE_NAME}" ]] || [[ -z "${NAMESPACE}" ]] || [[ -z "${SECRET_NAME}" ]]; then
+      echo "usage: write-config-secret.sh NODE_NAME NAMESPACE SECRET_NAME" >&2
+      exit 1
+    fi
+
+    echo "Getting providerID from node: ${NODE_NAME}"
+
     PROVIDER_ID=$(oc get node "${NODE_NAME}" -o json | jq -r '.spec.providerID')
     CLUSTER_ID=$(echo "${PROVIDER_ID}" | sed -E 's~ibm://.*/([^/]+)/.+~\1~g')
+
+    echo "Found clusterId: ${CLUSTER_ID}"
+
+    echo "Creating secret: ${SECRET_NAME}"
 
     kubectl create secret generic "${SECRET_NAME}" \
       --from-literal="clusterId=${CLUSTER_ID}" \
       --dry-run=client \
       --output=json | \
       kubectl apply -n "${NAMESPACE}" -f -
+
+    echo "Created secret: ${SECRET_NAME}"
